os: Visual Studio 2017

environment:
  global:
    cargoflags: --features "graphviz"
  matrix:
    - channel: nightly
    - channel: beta
    - channel: stable


install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv --default-toolchain %channel%
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - rustc -vV
  - cargo -vV

build_script:
    - cargo build --verbose %cargoflags%

test_script:
    - cargo test --verbose %cargoflags%

    - IF %channel%==nightly C:\msys64\usr\bin\bash -lc "CARGOFLAGS=%cargoflags% curl https://raw.githubusercontent.com/afonso360/rust-benchstats/master/benchstats.sh -sSf | sh"

branches:
  except:
    - benches
