os: Visual Studio 2017


environment:
  GH_TOKEN:
    secure: /u/eFQR83P03KKHQA3uBuZuR3ya/GcBWdztd7sqmKJllcn588RrmE0GNfDhqBYIN
  global:
    cargoflags: --features "graphviz"
  matrix:
    - channel: nightly
    - channel: beta
    - channel: stable

install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv --default-toolchain %channel%
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - rustc -vV
  - cargo -vV

build_script:
    - cargo build --verbose %cargoflags%

test_script:
    - cargo test --verbose %cargoflags%

    - IF %channel%==nightly (
        IF DEFINED APPVEYOR_PULL_REQUEST_NUMBER (
          C:\msys64\usr\bin\bash -vlc "CARGOFLAGS=\"%cargoflags%\" curl https://raw.githubusercontent.com/afonso360/rust-benchstats/master/benchstats.sh -sSf | sh"
        )
      )
