os: Visual Studio 2017

environment:
  global:
    cargoflags: --features "dot"
  matrix:
    - channel: nightly
    - channel: beta
    - channel: stable


install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv --default-toolchain %channel%
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - rustc -vV
  - cargo -vV

build_script:
    - cargo build --verbose %cargoflags%

test_script:
    - cargo test --verbose %cargoflags%
