os: Visual Studio 2017


environment:
  GH_TOKEN:
    secure: /u/eFQR83P03KKHQA3uBuZuR3ya/GcBWdztd7sqmKJllcn588RrmE0GNfDhqBYIN
  global:
    cargoflags: --features "graphviz"
  matrix:
    - channel: nightly
    - channel: beta
    - channel: stable

install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv --default-toolchain %channel%
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - rustc -vV
  - cargo -vV

build_script:
    - cargo build --verbose %cargoflags%

test_script:
    - cargo test --verbose %cargoflags%

    - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -Sy pacman"
    - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -Syuu"
    - IF "%channel%" == "nightly" (
        IF NOT DEFINED APPVEYOR_PULL_REQUEST_NUMBER (
          C:\msys64\usr\bin\bash -vlc "cd /c/projects/nom-lua && curl https://raw.githubusercontent.com/afonso360/rust-benchstats/master/benchstats.sh -sSf | CARGOFLAGS=\"%cargoflags%\" /bin/bash"
        )
      )
