language: rust

cache: cargo
addons:
  apt:
    sources:
      # Kcov dependencies
      - kalakris-cmake
    packages:
      # Kcov dependencies
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - cmake

env:
  - CARGO_FLAGS="--features graphviz"

rust:
  - beta
  - stable
  - nightly

os:
  - linux
  - osx

matrix:
  fast_finish: true

before_script:
  - export PATH="$PATH:$HOME/.cargo/bin"
  - which cargo-coverage || cargo install cargo-travis
  - which rustfmt || cargo install rustfmt

script:
  - cargo build --verbose ${CARGO_FLAGS}
  - cargo test --verbose ${CARGO_FLAGS}
  - cargo bench --verbose ${CARGO_FLAGS}
  - cargo doc --verbose ${CARGO_FLAGS}

after_success:
  - cargo fmt -- --write-mode=diff
  - if [ "$TRAVIS_OS_NAME" == "linux" ] && [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then
        cargo coveralls ${CARGO_FLAGS};
    fi

env:
  global:
    - secure: "oViHIJ5OL9/dEywpkMKlT4lyKCqjvMWMzCDS3eQMZfpHF1Q6Lhb2Bi+wu9GdbmNgqxXB8Gk192N+2pJiT33tUqlN31kULcZMwpEmCZL3cmdG5whWkyp5JMnHWTGbg7HCkrtoBVN9sJTkC7WALkQ0+YyrMOQBjRbiHCvhgnvVl4aRFYmI7UrJsAWkCLtKxvGm4dmXERekMjeh8rRfWb4AmEHF1gvW3UU5m3qbs5L1bPa0qAVPJ0IDE/sY/kBSUafNztiCCtIhIixR18bTWHUACCjwI6iSgprz1KjqaW4BIeBVL3BeBeD9oT72v++bzYqoOF8ZoqQ3KBiIQB5eV80TFDYQFLqT1OADRjQqE+OcRPwNp2Y4L58z2MsE3A9DNfp1ARRw4r/jXdNzz33Kg/EN2kRJb1SdfNJ1oUtka23WK5rAKXu8twoaOzKdwr6N9/xwBtIa6lRrD7xL5pcWr+vZhimmG93QJmfYrY74XyO8mUR2KBIKS8D6qUj0EPHqAaArasnSO/VZ1qdpYbMeMJj42GF1vEUy0HgfxVIjHZV4A2IhMK42pYxV9+zxcPzkxtRrLbmcqC5hjcVrrPchFWEHWsYeSqSLIdQBPuwVNG5ghC1muQzp/vIelJa+BZhkhlOyJ8BXIjrFf+Q1Z+1gKyYWWl7mzs4yBG+idTIYp890ASA="
