language: rust

cache: cargo
addons:
  apt:
    sources:
      # Kcov dependencies
      - kalakris-cmake
    packages:
      # Kcov dependencies
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - cmake

env:
  - CARGO_FLAGS="--features graphviz"

rust:
  - beta
  - stable
  - nightly

os:
  - linux
  - osx

matrix:
  fast_finish: true

before_script:
  - export PATH="$PATH:$HOME/.cargo/bin"
  - which cargo-coverage || cargo install cargo-travis
  - which rustfmt || cargo install rustfmt

script:
  - cargo build --verbose $CARGO_FLAGS
  - cargo test --verbose $CARGO_FLAGS
  - cargo doc --verbose $CARGO_FLAGS
  - if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then
      curl https://raw.githubusercontent.com/afonso360/rust-benchstats/master/benchstats.sh -sSf | sh ;
    fi

after_success:
  - cargo fmt -- --write-mode=diff
  - if [ "$TRAVIS_OS_NAME" == "linux" ] && [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then
        cargo coveralls $CARGO_FLAGS;
    fi

branches:
  except:
    - benches

env:
  global:
    - secure: "sSFcu9lXjE05oKS6I2rr6C0KdXyX+xIEb7GlmL+6s9k34DNNN5MigbwvNKSvop9qIoUPRpD9eULz+KC3vxjWc2xUFjwV+rZHXOBQrqG3p6GUHq80MZYfrVvPDSZD2zNod6zOgeCgIr/qJolTkcPnw01zrcFxv23yRlUJiHg3egHqDG3VbHNnD4ssqQuk5qEqHEMMlnRv4vaIo9KXTLD3hM3dRhJZtv2yJGg2oEtwzSSYEf43+51c01nDVvJMa2zrAbeBKQmI1or/924R2n+p4WGajcmtZIw7X5ks5VS3O0d5S5qFApq5lELnHsPc+uVMnCsRcVU+Qg3FITYw/4jH5M0v1O46MJfJHXMxEqTTLbAfIHVgs7IhXSzHjotxcPgoyz0GWu6afSyrhY6dCsKLEvjZLbLLlXEuMRffCS8zyxhNzni598rDMUTz1+r7XrjjQNNwHuBZQXVNel4224Zsu5J98HVx9zSZQZGFzPYUqFJR3dLWtwn0Zx83yS2vM2pKhcoL9V52Dd8UOrTiBtqGidHqtjAn8dQURq8390nFwrvnwXO5ObxZBWEST7P4X61lFiA26AH4Kt09A4TVUwE47MjUu5I1Tls45Ty3M8e+GCXujn7gg5AoyFF+TCbR3SG3ysRPQr+WCvsYh0nuGaIF8nduOUU+M8N9Nr0LMS6mK4A="
